apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: voteapp
  labels:
    role: frontend
    env: demo
spec:
  replicas: 2
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 25%
  selector:
    matchLabels:
      role: frontend
  template:
    metadata:
      labels:
        role: frontend
    spec:
      containers:
      - name: frontend
        image: cloudacademydevops/frontend:v8
        imagePullPolicy: Always
        env:
        - name: REACT_APP_APIHOSTPORT
          value: api-voteapp.apps.us-west-1.starter.openshift-online.com
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: / 
            port: 8080
          initialDelaySeconds: 2
          periodSeconds: 5
        readinessProbe:
          httpGet:
             path: /
             port: 8080
          initialDelaySeconds: 5
          periodSeconds: 5
          successThreshold: 1