apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: voteapp
  labels:
    role: frontend
    env: demo
spec:
  ports:
   - protocol: TCP
     port: 8080
  selector:
    role: frontend